// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteWebmotors.Infraestrutura.Config;

#nullable disable

namespace TesteWebmotors.Infraestrutura.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220402205448_primeiroMigration")]
    partial class primeiroMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TesteWebmotors.Dominio.Entidade.AnuncioWebmotors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ID");

                    b.Property<int>("Ano")
                        .HasColumnType("INT")
                        .HasColumnName("ano");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("modelo");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("Text")
                        .HasColumnName("observacao");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("INT")
                        .HasColumnName("quilometragem");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("versao");

                    b.HasKey("Id");

                    b.ToTable("tb_AnuncioWebmotors", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
